# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    role_hierarchy:
        ROLE_USER: ~
        ROLE_LECTEUR: ROLE_USER
        ROLE_EDITOR: ROLE_USER
        ROLE_AJOUT_DE_LIVRE: ROLE_ADMIN
        ROLE_EDITION_DE_LIVRE: ROLE_ADMIN
        ROLE_ADMIN: [ROLE_EDITION_D'ARTICLE, ROLE_AJOUT_D'ARTICLE, ROLE_SUPPRESSION_D'ARTICLE]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

        # admin_user_provider:
        #     id: App\Security\AdminUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # target: app_any_route

        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # target: admin_any_route

    access_control:
        # Admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }




        # Profile route
        - { path: ^/profile, roles: ROLE_USER }
